-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpicePageAssignments/maintenance/db/sql/bs_pageassignments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_pageassignments (
  pa_page_id INT NOT NULL,
  pa_assignee_key TEXT DEFAULT '' NOT NULL,
  pa_assignee_type TEXT DEFAULT '' NOT NULL,
  pa_position INT NOT NULL,
  PRIMARY KEY(
    pa_page_id, pa_assignee_key, pa_assignee_type
  )
);

CREATE INDEX pa_page_id ON bs_pageassignments (pa_page_id);
