-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpicePageAssignments/maintenance/db/sql/bs_pageassignments.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_pageassignments (
  pa_page_id INTEGER UNSIGNED NOT NULL,
  pa_assignee_key BLOB DEFAULT '' NOT NULL,
  pa_assignee_type BLOB DEFAULT '' NOT NULL,
  pa_position INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(
    pa_page_id, pa_assignee_key, pa_assignee_type
  )
);

CREATE INDEX pa_page_id ON /*_*/bs_pageassignments (pa_page_id);
